name: Manual gh_docs_bot Build

# Author: Robert Zheng
# created: 2026-01-12
# updated: 2026-01-12
# version: 1.0.0
# description: build and generate static website from markdown files to branch gh-pages

run-name: Manual gh_docs_bot Build by ${{ github.actor }}

on:
  workflow_dispatch:

permissions:
  contents: write

jobs:
  build-and-generate:
    runs-on: ubuntu-latest
    steps:
      - name: Build and Generate Site
        uses: Zheng-Bote/gha_ghpages@main
        with:
          template: 'theme/desktop/template.html'
          assets: 'theme/blue/assets'
          output: 'public'
          docs: '/docs'
